# GitLab CI template for CUE schema documentation on GitLab Pages
# Include in your .gitlab-ci.yml:
#   include:
#     - remote: 'https://gitlab.com/quicue/quicue-ci/-/raw/main/gitlab/cue-pages.yml'
#
# Generates:
#   - Schema documentation from cue def
#   - JSON export of definitions
#   - Browsable HTML at https://<namespace>.gitlab.io/<project>/

stages:
  - build
  - deploy

variables:
  CUE_VERSION: "0.11.1"
  SCHEMA_DIRS: "patterns vocab schemas"
  PROJECT_NAME: $CI_PROJECT_NAME

.cue-base:
  image: alpine:3.20
  before_script:
    - apk add --no-cache curl
    - curl -fsSL "https://github.com/cue-lang/cue/releases/download/v${CUE_VERSION}/cue_v${CUE_VERSION}_linux_amd64.tar.gz" | tar -xzf - -C /usr/local/bin cue

# Build schema documentation
pages:build:
  extends: .cue-base
  stage: build
  script:
    - mkdir -p public/schemas public/json
    # Find and process schema directories first to build manifest
    - |
      FOUND_SCHEMAS=""
      for dir in ${SCHEMA_DIRS}; do
        if [ -d "$dir" ]; then
          echo "Processing $dir..."
          SCHEMA_NAME=$(basename "$dir")
          cue def ./$dir > public/schemas/${SCHEMA_NAME}.cue 2>/dev/null || true
          if [ -s "public/schemas/${SCHEMA_NAME}.cue" ]; then
            FOUND_SCHEMAS="${FOUND_SCHEMAS} ${SCHEMA_NAME}"
          fi
        fi
      done
    # Generate manifest
    - |
      echo "{\"schemas\": [" > public/json/manifest.json
      FIRST=true
      for schema in ${FOUND_SCHEMAS}; do
        if [ "$FIRST" = true ]; then
          FIRST=false
        else
          echo "," >> public/json/manifest.json
        fi
        echo "\"${schema}\"" >> public/json/manifest.json
      done
      echo "]}" >> public/json/manifest.json
    # Generate index page with static links
    - |
      cat > public/index.html << 'INDEXEOF'
      <!DOCTYPE html>
      <html>
      <head>
        <title>Schema Documentation</title>
        <style>
          body { font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; }
          h1 { border-bottom: 2px solid #333; padding-bottom: 0.5rem; }
          pre { background: #f5f5f5; padding: 1rem; overflow-x: auto; border-radius: 4px; }
          a { color: #0066cc; }
          .schema-list { list-style: none; padding: 0; }
          .schema-list li { padding: 0.5rem 0; border-bottom: 1px solid #eee; }
        </style>
      </head>
      <body>
        <h1>Schema Documentation</h1>
        <p>Auto-generated schema documentation from CUE definitions.</p>
        <h2>Schemas</h2>
        <ul class="schema-list">
      INDEXEOF
    - |
      for schema in ${FOUND_SCHEMAS}; do
        echo "    <li><a href=\"schemas/${schema}.html\">${schema}</a></li>" >> public/index.html
      done
    - |
      cat >> public/index.html << 'INDEXEOF'
        </ul>
        <h2>Downloads</h2>
        <ul>
          <li><a href="json/manifest.json">manifest.json</a> - Schema list</li>
        </ul>
        <hr>
        <p><small>Generated by <a href="https://gitlab.com/quicue/quicue-ci">quicue-ci</a></small></p>
      </body>
      </html>
      INDEXEOF
    # Generate HTML pages for each schema
    - |
      for schema in ${FOUND_SCHEMAS}; do
        cat > public/schemas/${schema}.html << SCHEMAEOF
      <!DOCTYPE html>
      <html>
      <head>
        <title>${schema} Schema</title>
        <style>
          body { font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; }
          pre { background: #f5f5f5; padding: 1rem; overflow-x: auto; border-radius: 4px; font-size: 14px; line-height: 1.4; }
          a { color: #0066cc; }
        </style>
      </head>
      <body>
        <p><a href="../">Back to index</a></p>
        <h1>${schema}</h1>
        <pre><code>
      SCHEMAEOF
        cat public/schemas/${schema}.cue >> public/schemas/${schema}.html
        cat >> public/schemas/${schema}.html << 'SCHEMAEOF'
        </code></pre>
      </body>
      </html>
      SCHEMAEOF
      done
  artifacts:
    paths:
      - public
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Deploy to GitLab Pages
pages:
  stage: deploy
  dependencies:
    - pages:build
  script:
    - echo "Deploying to GitLab Pages..."
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
