// IP conflict resolution — authority hierarchy: Alpha > Bravo > Charlie
//
// When multiple sources report different IPs for the same VM,
// the highest-authority source wins. This file is typically
// auto-generated by a normalizer script; here it's hand-written
// to demonstrate the pattern.
//
// The rule: Alpha (hypervisor) is ground truth for IPs.
// Bravo (CMDB) may lag. Charlie (dependency graph) may have stale SID data.

package reconciliation

vms: {
	// ── Unanimous IPs (all sources agree) ──────────────────────
	"web-p01": primary_ip:  "198.51.100.10"
	"web-p02": primary_ip:  "198.51.100.11"
	"db-p01": primary_ip:   "198.51.100.20"
	"db-p02": primary_ip:   "198.51.100.21"
	"lb-p01": primary_ip:   "198.51.100.30"
	"ci-d01": primary_ip:   "203.0.113.10"
	"mon-p01": primary_ip:  "198.51.100.40"
	"bak-p01": primary_ip:  "198.51.100.50"
	"auth-p01": primary_ip: "198.51.100.60"

	// ── Conflict: Alpha wins over Bravo ────────────────────────
	// Bravo reports 198.51.100.71, Alpha reports 198.51.100.70
	"vpn-p01": primary_ip: "198.51.100.70" // CONFLICT: alpha wins over bravo:198.51.100.71

	// ── Single-source VMs (no conflict possible) ───────────────
	"ci-d02": primary_ip:      "203.0.113.11"  // alpha only
	"test-d99": primary_ip:    "203.0.113.99"  // alpha only
	"legacy-p10": primary_ip:  "192.0.2.10"    // bravo only
	"printer-p01": primary_ip: "192.0.2.20"    // bravo only
	"ext-api-01": primary_ip:  "203.0.113.200" // charlie only
}
