#!/usr/bin/env python3
"""Split bulk CUE export into individual operator/public/ files.

One CUE evaluation produces all data as JSON. This script splits it
into the individual files that operator/public/ expects, including
YAML (rundeck) and text (deploy script, index HTML) conversions.

Usage: python3 operator/split_bulk.py /tmp/bulk.json operator/public/
"""

import json
import os
import sys

try:
    import yaml
    HAS_YAML = True
except ImportError:
    HAS_YAML = False


def write_json(path, data):
    with open(path, "w") as f:
        json.dump(data, f, indent=2)


def write_text(path, text):
    with open(path, "w") as f:
        f.write(text)


def json_to_yaml(data):
    """Convert JSON-serializable data to YAML string."""
    if HAS_YAML:
        return yaml.dump(data, default_flow_style=False, sort_keys=False)
    # Fallback: use json with yaml-like formatting
    return json.dumps(data, indent=2)


def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <bulk.json> <output_dir>", file=sys.stderr)
        sys.exit(1)

    bulk_path = sys.argv[1]
    out_dir = sys.argv[2]

    with open(bulk_path) as f:
        bulk = json.load(f)

    os.makedirs(out_dir, exist_ok=True)
    os.makedirs(os.path.join(out_dir, "wiki"), exist_ok=True)

    # JSON files
    json_files = {
        "plan.json": bulk["plan"],
        "cluster-summary.json": bulk["cluster_summary"],
        ".bound_commands.json": bulk["bound_commands"],
        "notebook.ipynb": bulk["notebook"],
        "ops.json": bulk["ops_tasks"],
        "graph.jsonld": bulk["graph_jsonld"],
        "hydra.jsonld": bulk["hydra"],
        "interaction.json": bulk["interaction"],
    }
    for fname, data in json_files.items():
        write_json(os.path.join(out_dir, fname), data)

    # Rundeck: YAML
    write_text(os.path.join(out_dir, "rundeck-jobs.yaml"),
               json_to_yaml(bulk["rundeck"]))

    # Deploy script: text
    script_path = os.path.join(out_dir, "deploy.sh")
    write_text(script_path, bulk["script"])
    os.chmod(script_path, 0o755)

    # Index page: HTML generated by CUE
    write_text(os.path.join(out_dir, "index.html"), bulk["index_html"])

    # Build stats: computed by CUE, written for reference
    write_json(os.path.join(out_dir, ".build-stats.json"), bulk["stats"])

    # Wiki: extract nested file structure
    wiki_files = bulk.get("wiki", {}).get("files", {})
    for fpath, content in wiki_files.items():
        full = os.path.join(out_dir, "wiki", fpath)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        write_text(full, content)

    # Print stats (from CUE-computed values)
    s = bulk["stats"]
    print(f"  Plan: {s['layers']} layers, {s['resources']} resources, {s['gates']} gates")
    print(f"  Cluster: {s['providers']} providers, {s['resolved']} resolved commands")
    print(f"  Notebook: {s['nb_cells']} cells")
    print(f"  Rundeck: {s['rd_jobs']} jobs")
    print(f"  Wiki: {s['wiki_files']} markdown files")
    print(f"  Script: {s['script_lines']} lines")
    print(f"  Ops: {s['ops_tasks']} tasks ({s['ops_destructive']} destructive)")
    print(f"  JSON-LD: {s['jsonld_nodes']} resources")
    print(f"  Index: CUE-generated HTML")


if __name__ == "__main__":
    main()
